# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1di3e_xIjNH0PYHonki3L1qcBd-xMgQ5f
"""

!pip install streamlit
import streamlit as st

st.title("Basic Chatboat")


# Store chat history

if "message" not in st.session_state:
    st.session_state.message = []

# Display previous messages

for message in  st.session_state.message:
    with st.chat_message(message["role"]):
        st.write(message["content"])

# User input

user_input = st.chat_input("Enter your message ....")


if user_input:

    # Show user message
    st.session_state.message.append(
        {"role": "user", "content": user_input}
    )

    with st.chat_message("user"):
        st.write(user_input)

    # Simple chatbot logic
    if "hello" in user_input.lower():
        bot_reply = "Hello! How can I help you?"
    elif "name" in user_input.lower():
        bot_reply = "I am a simple Streamlit chatbot."
    elif "bye" in user_input.lower():
        bot_reply = "Goodbye! Have a great day."
    else:
        bot_reply = "Sorry, I don't understand that yet."

    # Show bot response
    st.session_state.message.append(
        {"role": "assistant", "content": bot_reply}
    )

    with st.chat_message("assistant"):
        st.write(bot_reply)